name: Execute standard blank run

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'How long in seconds should the job execute?'
        type: number
        default: 5
  workflow_call:
    inputs:
      duration:
        description: 'How long in seconds should the job execute?'
        type: number
        default: 5

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for x in {1..${{ inputs.duration }}}
          do 
            echo "Sleeping count: $x"
          done 
      
