name: Various steps sample

on:
  workflow_dispatch:
  workflow_call:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: actions/setup-dotnet@v1
      - uses: actions/setup-node@v1
      - uses: actions/setup-go@v1
      - uses: actions/setup-java@v1
        with:
           java-version: 17
      - name: Run a multi-line script
        run: |
          echo In this workflow, we have setup:
          echo Various tools and languages
